# Generated by Django 4.1.6 on 2023-05-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('fees', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
