# Generated by Django 4.2 on 2023-05-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_trainers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trainers',
            table='trainers',
        ),
    ]
