# Generated by Django 4.2 on 2023-05-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_alter_trainers_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'hosttable',
            },
        ),
    ]
