# Generated by Django 4.1.6 on 2023-06-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0007_enquiry_adhaarno_enquiry_clgname_enquiry_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=55)),
                ('address', models.CharField(max_length=55)),
                ('contact', models.CharField(max_length=55)),
                ('education', models.CharField(max_length=55)),
                ('date', models.CharField(max_length=55)),
                ('adhaarno', models.CharField(max_length=55, null=True)),
                ('clgname', models.CharField(max_length=55, null=True)),
                ('reference', models.CharField(max_length=55, null=True)),
            ],
            options={
                'db_table': 'esnrollments',
            },
        ),
    ]
