# Generated by Django 4.1.6 on 2023-06-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0008_enrollments'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollments',
            name='course',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
