# Generated by Django 4.2 on 2023-06-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0012_delete_staff_trainerslogin_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='password',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
