# Generated by Django 4.1.6 on 2023-06-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0013_enquiry_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=55)),
                ('name', models.CharField(max_length=55)),
                ('date', models.CharField(max_length=55)),
                ('status', models.CharField(max_length=55)),
            ],
            options={
                'db_table': 'attendence',
            },
        ),
    ]
